# Generated by Django 3.2.13 on 2023-12-02 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время - 1'), django.core.validators.MaxValueValidator(120, message='Максимальное время - 120')], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
